name: Bug Report
description: Report a reproducible bug or regression.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened, in one or two sentences?
      placeholder: "Map does not fit when selecting X_NOR..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide precise steps.
      placeholder: |
        1. Open example
        2. Select country ID X_NOR
        3. Press Fit
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
    validations:
      required: true

  - type: input
    id: package_version
    attributes:
      label: Package Version
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: flutter_version
    attributes:
      label: Flutter Version
      placeholder: "3.24.x"
    validations:
      required: true

  - type: dropdown
    id: platforms
    attributes:
      label: Platform(s)
      multiple: true
      options:
        - iOS
        - Android
        - Web
        - macOS
        - Windows
        - Linux
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      description: Paste logs or attach screenshots if relevant.
