name: Feature Request
description: Propose an improvement or new capability.
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem / Motivation
      description: What problem are you trying to solve?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: Describe the desired API/behavior.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternatives you’ve considered?
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Links, references, screenshots.
    validations:
      required: false
